openapi: 3.1.0
info:
  version: 1.0.0
  title: Simple Petstore
  description: This is a slimmed down single path version of the Petstore definition.
servers:
  - url: https://httpbin.org
paths:
  '/pet/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      operationId: A
      tags:
        - pet
      summary: Update a pet
      description: This operation will update a pet in the database.
      responses:
        '400':
          description: Invalid id value
      security:
        - apiKey: []
    get:
      operationId: B
      tags:
        - pet
      summary: Find a pet
      description: This operation will find a pet in the database.
      responses:
        '400':
          description: Invalid status value
      security: []
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: basic
